# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    curl \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install poetry

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Set the working directory
WORKDIR /app

# Copy the pyproject.toml and poetry.lock files from the root directory
COPY ./pyproject.toml ./poetry.lock ./

# Install dependencies
RUN poetry install --no-root

# Copy the 3-feature-pipeline and any other necessary directories
COPY ./3-feature-pipeline ./3-feature-pipeline
COPY ./core ./core
COPY ./scripts ./scripts
COPY ./settings.py ./settings.py

# Set the PYTHONPATH environment variable
ENV PYTHONPATH=/app

RUN chmod +x /app/scripts/bytewax_entrypoint.sh

# Command to run the Bytewax pipeline script
CMD ["/app/scripts/bytewax_entrypoint.sh"]

